In [2]:
mass = 20 
acceleration = 10
force = mass * acceleration
print(force)

200


In [4]:
f = force
m = mass
a = acceleration
if (f >= 200):
    print ('the force is big')
else:
    print ('the force is small')

the force is big


In [13]:
power = 70 / 7
print (power)

10.0


In [2]:
def power(a,b):
    power = a ** b
    print (power)


power(2,2)

4


In [1]:
item = False
while item == True:
    print (item)



In [22]:
import numpy as np
ln = np.array([2,3,5])
bh = np.array([4,2,4])
prd = np.dot(ln,bh)
print(prd)

34


prd2 = (ln * bh).sum()
print(prd2)

In [36]:
cmt_dt = np.array([[75,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70]])
cmt_dt.shape

(5, 3)

In [30]:
ln

array([2, 3, 5])

In [34]:
np.matmul(cmt_dt,ln)

array([566., 766., 866., 518., 776.])

In [35]:
cmt_dt @ ln

array([566., 766., 866., 518., 776.])

In [37]:
cmt_dt * ln

array([[150, 201, 215],
       [182, 264, 320],
       [174, 402, 290],
       [204, 129, 185],
       [138, 288, 350]])